### ISSUE TITLE
Specification of spectral library files in param.txt (DDA)

### ISSUE THREAD

**Issue by oliveralka** [MetaboKit/MetaboKit#3]
Hi, 

I have a suggestion in terms of specification of the spectral library files. 

Currently, the spectral libraries are specified via the param.txt 
```
library
msdial    
``` 
Unfortunately, the tool "DDAscore.py" will currently look at a hard-coded location for a specific file name 
```
python ~/Documents/work/software/MetaboKit/src/DDAscore.py  
[('M+H', (1.007825, 1, '+')), ('M+Na', (22.989218, 1, '+')), ('M+K', (38.963158, 1, '+'))]
Traceback (most recent call last):
  File "/Users/alka/Documents/work/software/MetaboKit/src/DDAscore.py", line 336, in <module>
    lib_ent=get_cpds()
  File "/Users/alka/Documents/work/software/MetaboKit/src/DDAscore.py", line 286, in get_cpds
    lib_dict.update(read_lib(libpath))
  File "/Users/alka/Documents/work/software/MetaboKit/src/DDAscore.py", line 229, in read_lib
    it_cpd=iter(line.rstrip() for line in open(libpath))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/alka/Documents/work/software/MetaboKit/src/libs/MSMS-Public-Pos-VS12.msp'
```
I downloaded a library with a different filename `MSDIAL-InsilicoMSMS-Lipids-Pos.msp` which could not be used, unless copying it to `/Users/alka/Documents/work/software/MetaboKit/src/libs` and rename the file to `MSMS-Public-Pos-VS12.msp'.

For making the tool more user friendly I would suggest that either the filename and/or the path+filename can be set in the param.txt. 

e.g. new_param.txt 
```
library
/Volumes/ExternalVolume/MetaboKIT/test/MSDIAL-InsilicoMSMS-Lipids-Pos.msp
``` 

edit: If the parsing is dependent on the type of library e.g. hmdb (.xml), msdial (.msp) - something like this might be sufficient to use without too much refactoring.
```
library
msdial /Volumes/ExternalVolume/MetaboKIT/test/MSDIAL-InsilicoMSMS-Lipids-Pos.msp
```

**Comment by Lypsi** [comment]
Hi,

first thank you for this nice and fast tool.

Is the issue closed and therefore possible to load own libraries in the next release?

Otherwise, is there a possibility to load custom libraries?

Could you share the code to generate the library files out of the *.msp files?

**Comment by guoshou** [comment]
Hi,
I have updated it here: https://github.com/MetaboKit/MetaboKit/releases
In "example_data_dir", "my_lib.txt" shows an example of a custom library.
"NAME", "PRECURSORMZ", "NUM PEAKS" are mandatory fields, "RETENTIONTIME", "INCHIKEY", "PRECURSORTYPE" are optional, the rest will not be used.
