### ISSUE TITLE
Data processing error: DDA Metabolomics

### ISSUE THREAD

**Issue by s-kotwal** [MetaboKit/MetaboKit#4]
Hi,

I am analyzing plant metabolites using LC-QTOF-MS (Agilent 6546), first in DDA mode then will try DIA mode later.
While processing the DDA data in MetaboKit, I am getting the following error in command:

"thread 'main' panicked at src\parse.rs:144:31:
array type not set
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

I was able to process the example dataset provided in the folder when downloading MetaboKit.
Any help is greatly appreciated.

Thanks,

Shashi

**Comment by guoshou** [comment]
please share one of your mzML files for me to check, thanks.

**Comment by s-kotwal** [comment]
I’ve responded to your email with more details about data processing.

thanks

**Comment by guoshou** [comment]
I have checked my inbox and junk folders, did not receive anything from you.

**Comment by hwchoi912** [comment]
Dear Shashi, can you send us the email one more time? Also it is always best if you share one sample file with us for troubleshooting. We always keep it confidential and do not ask anything in return - Hyungwon

**Comment by s-kotwal** [comment]
Hello Dr. Choi & Guoshou, I've resent the email that has more information about how data file was converted to mzML then processed, as well as the mzML file.

May look for email from: ssk202@scarletmail.rutgers.edu or kotwal.shashikant7@gmail.com

Best,
Shashi
